### ISSUE TITLE
YAML anchor 

### ISSUE THREAD

**Issue by nmaurer23** [cloudfoundry-incubator/spiff#22]
For me it looks like there is a bug in spiff if the source yml file is
using YAML anchor. 

Something like this

```
test1: &test1
  a: 2
  b: 2
test2:
  <<: *test1
```

should merge the values from test1 into test2.

Currently this example results in:

```
test1:
  a: 2
  b: 2
test2:
  <<:
    a: 2
    b: 2
```

after processing the yml file with spiff.

So the <<: is used as a key and the values are added with the wrong indent.
