### ISSUE TITLE
<<: doesn't work for arrays

### ISSUE THREAD

**Issue by vito** [cloudfoundry-incubator/spiff#27]
the example I put in the release doesn't actually work

```yaml
bar:
  - 1
  - 2

foo:
  - 3
  - <<: (( bar ))
  - 4
```

spiff merge <that file> yields:

```yaml
bar:
- 1
- 2
foo:
- 3
- {}
- 4
```

**Comment by silval** [comment]
Hello,
"<<:" does not work for merging maps either, at least not as advertised in the [documentation page](https://github.com/cloudfoundry-incubator/spiff#merging-maps).

Is there any plans/expectation to fix this issue?

**Comment by keymon** [comment]
:+1:

**Comment by keymon** [comment]
OK, I found that it only works with `<<: ((merge))`, but not with other random thing (e.g. `<<: ((foo))`). You can see a working example [in the test](https://github.com/cloudfoundry-incubator/spiff/blob/master/flow/flow_test.go#L530)

### Failure example

For instance, this **DOES NOT** work:

 * `common-manifest.yml`:

```
---
releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=190
    sha1: a0260b8cbcd3fba3a2885ddaa7040b8c4cb22a49
  - <<: (( cpi_releases ))
```

 * `aws-manifest.yml`:

```
---
cpi_releases:
  - name: bosh-google-cpi
    url: http://storage.googleapis.com/bosh-stemcells/bosh-google-cpi-5.tgz
    sha1: c5de3053f233e6ef42c2a4228fa94179d955cc84
```

### working example

But this **DOES WORK**:

```
---
releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=190
    sha1: a0260b8cbcd3fba3a2885ddaa7040b8c4cb22a49
  - <<: (( cpi_releases ))
```

 * `aws-manifest.yml`:

```
---
cpi_releases:
  - name: bosh-google-cpi
    url: http://storage.googleapis.com/bosh-stemcells/bosh-google-cpi-5.tgz
    sha1: c5de3053f233e6ef42c2a4228fa94179d955cc84
```

# Workaround

You must do the expansion in the same name somewhere else, in the example above, `aws-manifest.yml`:

```
---
releases: (( cpi_releases ))
cpi_releases:
  - name: bosh-google-cpi
    url: http://storage.googleapis.com/bosh-stemcells/bosh-google-cpi-5.tgz
    sha1: c5de3053f233e6ef42c2a4228fa94179d955cc84

```

**Comment by keymon** [comment]
And if you want to merge several hashes, you can do something like this:

* `final.yml`: 
   ```
---
jobs: ((merge))
```
* `job1.yml`: 
   ```
---
jobs: 
 - <<: ((merge))
 - name: job1
    option1: true
```
* `job2.yml`: 
   ```
---
jobs: 
 - <<: ((merge))
 - name: job2
    option2: true
```
* `job3.yml`: 
   ```
---
jobs: 
 - <<: ((merge))
 - name: job3
    option3: true
```

`spiff final.yml job{1,2,3}.yml` will expand in:

```
---
jobs:
 - name: job1
    option1: true
 - name: job2
    option2: true
 - name: job3
    option3: true

```
