### ISSUE TITLE
Merge of array and value works differently

### ISSUE THREAD

**Issue by james-masson** [cloudfoundry-incubator/spiff#30]
Take 3 files - merge them together:

riak-core.yml

```
jobs:
- name: riak
  template: riak
  instances: (( merge ))
  networks:
  - name: riak-network
    static_ips: (( merge ))
```

4_server_toggle.yml

```
jobs:
- name: riak
  instances: 4
  networks:
  - name: riak-network
    static_ips:
    - 10.244.3.6
    - 10.244.3.10
    - 10.244.3.14
    - 10.244.3.22
```

env.yml

```
jobs:
- name: riak
  instances: 3
  networks:
  - name: riak-network
    static_ips:
    - 10.244.3.6
    - 10.244.3.10
    - 10.244.3.14
```

```
spiff merge riak-core.yml 4_server_toggle.yml env.yml
```

results in instances = 3, but with 4 IPs in the static IPs array

```
spiff merge riak-core.yml env.yml 4_server_toggle.yml
```

results in instances = 4, but with 3 IPs in the static IPs array

repeating the 4_server_toggle.yml reference leads to the "correct" output

```
spiff merge riak-core.yml 4_server_toggle.yml env.yml 4_server_toggle.yml
```

results in instances = 4, with 4 IPs in the static IPs array

Is this expected behavior? spiff version 1.0.0 on Mac

thanks

James M
