### ISSUE TITLE
Spiff merge seems to be nondeterministic.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-incubator/spiff#34]
Im using spiff for merging CF templates, and Ive noticed that using spiff merge yields a couple of different results when using the same templates.

```
# repeat is zsh specific
$ (repeat 100 ../../cf-release/generate_deployment_manifest vsphere hehe.yml | md5sum ) | sort | uniq -c
     12 1347cc537cab4d703abcb8cef63cdd44  -
     17 2ae0e8eb50deca14c86663d611f47486  -
     19 2d19dffe513c56d22b4211e78dcbe441  -
     14 5c7b72eb080a3849109e7b59c2dded89  -
     11 67ef6a2ebee92aa90edf63b9b167ee5f  -
     14 75e3e55e9c4415bbcc1d5a7cecd7b672  -
     13 773bd7f0cde35ef78f759d5b6e5400e3  -
$ (repeat 100 ../../cf-release/generate_deployment_manifest vsphere hehe.yml | md5sum ) | sort | uniq -c
     10 1347cc537cab4d703abcb8cef63cdd44  -
     13 2ae0e8eb50deca14c86663d611f47486  -
     18 2d19dffe513c56d22b4211e78dcbe441  -
     18 5c7b72eb080a3849109e7b59c2dded89  -
     17 67ef6a2ebee92aa90edf63b9b167ee5f  -
     11 75e3e55e9c4415bbcc1d5a7cecd7b672  -
     13 773bd7f0cde35ef78f759d5b6e5400e3  -
# Notice how the distribution changes between runs aswell
```

```
$ pwd && git rev-parse HEAD
/home/simon/go/src/github.com/cloudfoundry-incubator/spiff
96389b2819f0324de7b90cb4609208100a1f5cfb

$ spiff --v
spiff version 1.0.2

$ pwd && git rev-parse HEAD 
/home/simon/src/cf-release
c4dfff2fe703fd05c4a9044b492d8e4abfb4ac6b # Aka tag v173
```

Here is the hehe.yml (minimum that is needed for spiff to manage to merge)

```

---
name:
director_uuid:

meta:
  stemcell:
    name:

networks:
  - name: cf1
    subnets:
      - range:
        static:
          - 10.230.8.1 - 10.230.8.20

  - name: cf2
    subnets:
      - range:
        static:
          - 10.230.9.1 - 10.230.9.20

properties:

  dea_next:
    memory_mb:
    disk_mb:

  loggregator_endpoint:
    shared_secret:

  cc:
    bulk_api_password:
    staging_upload_user:
    staging_upload_password:
    db_encryption_key:
    srv_api_uri:

  uaa:
    jwt:
      signing_key:
      verification_key:
    cc:
      client_secret:
    admin:
      client_secret:
    clients:
      login:
        secret:
      cc_service_broker_client:
        secret:
      developer_console:
        secret:
      app-direct:
        secret:
      support-services:
        secret:
      servicesmgmt:
        secret:
      space-mail:
        secret:
    scim:
      users:
    batch:
      username:
      password:

  nats:
    user:
    password:

  router:
    status:
      user:
      password:
```

Please let me know if there is any additional information needed!
