### ISSUE TITLE
spiff uses lots of CPU and eventually runs out of memory if static IP ranges are misconfigured

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-incubator/spiff#82]
If the static IP ranges are configured such that the upper-bound of the range is less than the lower-bound of the range (see below for example), spiff uses lots of CPU and RAM and eventually runs out of memory.

We are unlikely to fix this, but it warrants creating this issue as a notice.

Example:

```
  subnet_configs:
  - name: mysql1
    type: manual
    subnets:
    - range: 10.0.21.0/24
      reserved:
        - 10.0.24.2 - 10.10.24.9
        - 10.0.24.130 - 10.10.24.254
      static:
        - 10.0.24.10 - 10.0.14.14
```

Notice also that the IPs do not exist inside the range specified (`10.0.21.0/24` vs `10.0.24.x`).
