### ISSUE TITLE
Are there any plans for support for including external text resource files?

### ISSUE THREAD

**Issue by kinjelom** [cloudfoundry-incubator/spiff#86]
Something like a new dynaml expression for including resources would be very useful for me...
Example:

### template.yml:
```yaml
uaa:
    admin:
      client_secret: AdminSecret
    ca_cert: ((resource: resource-1-key))
```

### resource file  `/path-to/text-file-1`:
```
-----BEGIN CERTIFICATE-----
XYZ
-----END CERTIFICATE-----
```

### spiff command parameters:
```bash
spiff merge template.yml [template2.ymll ...] \
resource:resource-1-key=/path-to/text-file-1 [resource:resource-2-key=/path-to/text-file-2]
```
### output yaml file:
```yaml
uaa:
    admin:
      client_secret: AdminSecret
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      XYZ
      -----END CERTIFICATE-----
```
Some ideas from StackOverflow: https://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another
